Hw3
prefabsprout/backend_testing_course pull request #3
Opened 2021-07-08 13:15 UTC by prefabsprout

2021-07-08 22:08 UTC, prefabsprout commented on README.md
> +response specification, метод для получения готового объекта из Response.
`request specification` и `response specification` не использовал, ибо, если я верно понял, это фишка REST-assured. Писать кастомные спецификации под `requests`+`pytest` для тестирования данного конкретного сервиса, имхо, нет смысла.

2021-07-09 09:50 UTC, zhidelev requested changes
Поправить комменты 🙂

2021-07-09 09:50 UTC, zhidelev commented on HW3/test/testclasses/trello_api_base_class.py
> +        return self
Думаю, что стоит передавать `key` и `token` в инициализаторе класса. И если надо их обновлять, то просто через изменение `property`.

2021-07-09 09:50 UTC, zhidelev commented on HW3/test/testclasses/trello_api_base_class.py
> +        return self
Не совсем понял зачем возвращается сам объект. Лучше возвращать объект ответа, его можно проверить на `status code` и прочее. Не присваивать его `self.api_response` , а сразу возвращать.

2021-07-09 09:50 UTC, zhidelev commented on HW3/test/testclasses/trello_api_base_class.py
> +        self.parameters = dict()
Для чего всегда присваивается пустой `dict` ? 🙂

2021-07-09 09:50 UTC, zhidelev commented on HW3/test/testclasses/trello_api_boards_сlass.py
> +        return self
Переделать через использование `property`.

2021-07-09 09:50 UTC, zhidelev commented on HW3/test/trello_api_test_suite.py
> +        trello_api_boards = TrelloAPIBoardsClass()
Сделать создание `TrelloAPIBoardsClass()` через фикстуру, чтобы не создавать инстанс в каждом тестовом классе.

2021-07-09 09:50 UTC, zhidelev commented on HW3/test/trello_api_test_suite.py
> +            .should_status_code_be_as_expected(200)
Разделить это тест на 3 кейса.

2021-07-09 11:07 UTC, prefabsprout commented on HW3/test/testclasses/trello_api_base_class.py
> +        self.parameters = dict()
Я думал поначалу обойтись без создания новых объектов для каждого нового запроса и думал таким образом сбрасывать атрибут с параметрами. Но сейчас да, эта штука избыточна

2021-07-12 13:47 UTC, zhidelev approved these changes
👍

2021-07-12 15:46 UTC, merged